services:
  postgres:
    image: postgres:16-alpine
    container_name: cron-weather-postgres
    environment:
      POSTGRES_USER: ${PG_USER:-app}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-app}
      POSTGRES_DB: ${PG_DB:-app}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${PG_USER:-app} -d ${PG_DB:-app}" ]
      interval: 5s
      timeout: 3s
      retries: 20

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cron-weather-app
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      IN_DOCKER: "1"
      ENV: ${ENV:-local}
      TG_BOT_TOKEN: ${TG_BOT_TOKEN}
      PG_HOST: ${PG_HOST:-postgres}
      PG_PORT: ${PG_PORT:-5432}
      PG_USER: ${PG_USER:-app}
      PG_PASSWORD: ${PG_PASSWORD:-app}
      PG_DB: ${PG_DB:-app}
      PG_SSLMODE: ${PG_SSLMODE:-disable}
    restart: unless-stopped
    env_file:
      - .env

volumes:
  pgdata:
